import 'package:get/get.dart';

class LocalizationService extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'fa': {
          'NameApp': 'دکتر اپ',
          'category': 'دسته بندی',
          'GeneralPractitioner': 'عمومی',
          'Dentist': 'دندان',
          'cardiologist': 'قلب',
          'Neurologist': 'مغز و اعصاب',
          'TopDoctors': "پزشک های برتر",
          'Home': 'خانه',
          'Search': 'جستجو',
          'appointments': 'نویت ها',
          'Settings': 'تنظیمات',
          'doctor': 'دکتر',
          'Doctor specialty': 'تخصص',
          'DarkMode': 'حالت شب',
          'Language': 'زبان',
          'Location': 'منطقه',
          'SavedDoctors': 'پزشک های ذخیره شده',
          'Version': 'نسخه',
          'Logout': 'خروج',
          'Profile': 'نمایه',
          'Hello': 'سلام',
          'Search by': 'جستجو با توجه به',
          'Shiraz': "شیراز",
          'Empty': "خالی",
          'date and time': "تاریخ و ساعت",
          'Login': 'ورود',
          'Sign Up': 'ثبت نام',
          'Wellcome': 'خوش آمدید',
        },
        'en': {
          'NameApp': "Dr App",
          'category': 'Category',
          'GeneralPractitioner': 'General Practitioner',
          'Dentist': 'Dentist',
          'cardiologist': 'Cardiologist',
          'Neurologist': 'Neurologist',
          'TopDoctors': 'Top Doctors',
          'Home': 'Home',
          'Search': 'Search',
          'appointments': 'appointments',
          'Settings': 'Settings',
          'doctor': 'doctor',
          'Doctor specialty': 'Doctor specialty',
          'DarkMode': 'Dark Mode',
          'Language': 'Language',
          'Location': 'Location',
          'SavedDoctors': 'Saved Doctors',
          'Version': 'Version',
          'Logout': 'Logout',
          'Profile': 'Profile',
          'Hello': 'Hi',
          'Search by': 'Search by',
          'Shiraz': 'Shiraz',
          'Empty': 'Empty',
          'date and time': 'Date and Time',
          'Login': 'Login',
          'Sign Up': 'Sign Up',
          'Wellcome': 'Wellcome',
        },
      };
}
